---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-cm
  labels:
{{ include "app.labels" . | indent 4 }}
data:
  REACT_APP_HOME_SERVER_URL: "https://synapse.{{- .Values.settings.hostname -}}"
  REACT_APP_POLL_DESCRIPTION_REQUIRED: "true"
  REACT_APP_POLL_SHOW_LIVE_RESULT_BY_NAME: "true"
{{- if .Values.nginx.ipv4Only }}
---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: "{{ include "app.fullname" . }}-nginx-configs"
  labels:
{{ include "app.labels" . | indent 4 }}
data:
  listen.conf: |
    listen 8080;
{{- end }}
